{% set name = "opentelemetry-exporter-google-cloud" %}
{% set version = "0.18b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb5a01892612c6cb963f0f21012d6889469923a76b2c157ff0b2212c486015c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - google-cloud-monitoring <2.0.0
    - google-cloud-trace >=0.24.0,<1.0.0
    - opentelemetry-api =={{ version }}
    - opentelemetry-sdk =={{ version }}
    - python >=3.5

test:
  imports:
    - opentelemetry.exporter.cloud_trace
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/tree/master/opentelemetry-exporter-google-cloud
  summary: OpenTelemetry Google Cloud Integration
  license: Apache-2.0
  license_file: LICENSE
  description: Provides OpenTelemetry Python exporters for Google Cloud Platform.
  doc_url: https://google-cloud-opentelemetry.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twoodwark
